name: Release

on:
  release:
    types: [published]

jobs:
  manifest_bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master
      - name: Bump manifest
        run: |
          sed -i 's/v0.0.0/${{ steps.version.outputs.version }}/' custom_components/baby_buddy_homeassistant/manifest.json